#cloud-config
package_upgrade: true
packages:
  - lamp-server
  - unzip
runcmd:
  - wget https://github.com/opsgility/lab-support-public/raw/master/linux-lift-shift/onprem/osticket.zip
  - unzip osticket.zip -d /var/www/html
- - chown -R demouser:www-data /var/www/html
  - mv /var/www/html/index.html /var/www/html/index.html.org
  - systemctl restart apache2